[project]
name = "InfoField__StorageChronoIndexBridge"
version = "0.1.0"
description = "Establishing bridge between ChronoIndex and Storage layer"
authors = ["DeadlySquad13 <46250621+DeadlySquad13@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]

[tasks]
#   `break-system-packages` option is set to mute ArchLinux notifications that we
# are installing package globally (in reality we aren't, it's just pixi venvs
# are recognized as global).
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check --break-system-packages -e ."
build = "echo test"
# symlink-manager = "python src/symlink_manager/main.py"
start = "symlink-manager"

[dependencies]
python = ">=3.8"
plyvel = ">=1.5.1,<2"

[feature.test]
tasks = { test = "pytest" }
pypi-dependencies = { InfoField__StorageChronoIndexBridge = { path = "./", editable = true }, pytest = "==6.2.5", pytest-cov = "==2.12.1" }

[feature.lint.tasks]
lint-check = "flake8 src"

format = "black src"
format-check = "black --check --diff src"

types-check = "mypy src"

order-imports = "isort src"
order-imports-check = "isort --check --diff src"

[feature.lint.pypi-dependencies]
flake8 = "==7.0.0"
tox = "==3.24.3"
mypy = "==1.9.0"
black = "==24.3.0"
isort = "==5.13.2"

[feature.pre-commit]
tasks = { pre-commit-check = "pre-commit run --all-files" }
pypi-dependencies = { InfoField__StorageChronoIndexBridge = { path = "./", editable = true }, pre-commit = "==3.7.0" }

[environments]
default = []
dev = ["test", "lint", "pre-commit"]

[pypi-dependencies]
pathspec = ">=0.12.1, <0.13"

[package]
name = "InfoField__StorageChronoIndexBridge"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
hatchling = "==1.26.3"
